


services:
  
  pedalhunt-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: pedalhunt-api
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app
    hostname: pedalhunt-api
    container_name: pedalhunt-api
    networks:
      - pedalhunt
    ports:
      - 8000:8000
    

networks:
  pedalhunt:
    


